version: "3.9"
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: stocks
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"

  airflow:
    image: apache/airflow:2.9.3
    environment:
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
    command: bash -c "airflow db upgrade && airflow webserver & airflow scheduler"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts
    ports:
      - "8080:8080"
    depends_on:
      - postgres
